[package]
name = "advent-12-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
pathfinding = "4.1.1"
anyhow = "1.0"
took = "0.1"
